global using ImGuiNET;
global using Dalamud.Game.ClientState.Conditions;
global using ECommons.DalamudServices;
global using ECommons.GameFunctions;
global using SomethingNeedDoing.Attributes;
global using SomethingNeedDoing.Core;
global using SomethingNeedDoing.Core.Exceptions;
global using SomethingNeedDoing.Utils;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Numerics;
global using static ECommons.GenericHelpers;
global using static SomethingNeedDoing.Plugin;
global using Callback = ECommons.Automation.Callback;
global using Sheets = Lumina.Excel.Sheets;
global using Player = ECommons.GameHelpers.Player;
